using System.Reflection;
using MiniOrm.Attributes;

namespace MiniOrm.Database;

public class TableBuilder
{
    public string GenerateCreateTableSql(Type entityType)
    {
        var tableAttr = entityType.GetCustomAttribute<TableAttribute>();
        if (tableAttr == null)
            throw new Exception($"Class {entityType.Name} is missing [Table] attribute.");

        var tableName = tableAttr.Name;

        var properties = entityType.GetProperties();

        var columns = new List<string>();

        foreach (var property in properties)
        {
            var columnAttr = property.GetCustomAttribute<ColumnAttribute>();
            if (columnAttr == null) continue;

            var postgreType = MapCSharpTypeToPostgres(property.PropertyType, columnAttr);

            var columnSql = $"{columnAttr.Name} {postgreType}";

            var primaryKeyAttr = property.GetCustomAttribute<PrimaryKeyAttribute>();
            if (primaryKeyAttr != null)
            {
                columnSql = primaryKeyAttr.AutoGenerated
                    ? $"{columnAttr.Name} SERIAL PRIMARY KEY"
                    : $"{columnSql} PRIMARY KEY";
            }

            if (!columnAttr.IsNullable && primaryKeyAttr == null)
            {
                columnSql += " NOT NULL";
            }

            if (columnAttr.DefaultValue != null)
            {
                columnSql += $" DEFAULT {columnAttr.DefaultValue}";
            }
            
            var uniqueAttr = property.GetCustomAttribute<UniqueAttribute>();
            if (uniqueAttr != null)
            {
                columnSql += " UNIQUE";
            }
            
            var foreignKeyAttr = property.GetCustomAttribute<ForeignKeyAttribute>();
            if (foreignKeyAttr != null)
            {
                columnSql += $" REFERENCES {foreignKeyAttr.ReferenceTable}({foreignKeyAttr.ReferenceColumn})";
            }
            
            columns.Add(columnSql);
        }

        return $"CREATE TABLE {tableName} ({string.Join(", ", columns)})";
    }

    private string MapCSharpTypeToPostgres(Type type, ColumnAttribute columnAttr)
    {
        if (type.IsEnum) return "INTEGER";
        if (type == typeof(int)) return "INTEGER";
        if (type == typeof(string)) return $"VARCHAR({columnAttr.Length})";
        if (type == typeof(decimal)) return "DECIMAL";
        if (type == typeof(float)) return "REAL";
        if (type == typeof(DateTime)) return "TIMESTAMP";
        
        throw new NotSupportedException($"{type.Name} is not supported.");
    }
}